swagger: '2.0'
info:
  title: revised API
  description: Data API for revised-web.herokuapp.com
  version: "1.0.0"
host: revised-server.herokuapp.com
schemes:
  - http
basePath: /v1
produces:
  - application/json
paths:
  /books:
    get:
      summary: Books
      description: |
        The Books endpoint returns information about the books with
        available data on reVISed.
      tags:
        - Books
      responses:
        200:
          description: An array of books
          schema:
            type: object
            properties:
              books:
                type: array
                items:
                  $ref: '#/definitions/Book'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /books/{id}:
    get:
      summary: Books
      description: Returns the single book with the matching ID.
      parameters:
        - name: id
          in: path
          description: The ID of the book to get
          required: true
          type: integer
          minimum: 1
      tags:
        - Books
      responses:
        200:
          description: The requested book
          schema:
            type: object
            properties:
              book:
                $ref: '#/definitions/Book'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /resources:
    get:
      summary: Resources
      description: |
        The Resources endpoint returns information about all the resources
        for any books on reVISed.
      tags:
        - Resources
      responses:
        200:
          description: An array of resources
          schema:
            type: object
            properties:
              resources:
                type: array
                items:
                  $ref: '#/definitions/Resource'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /resources/{id}:
    get:
      summary: Resources
      description: Returns the single resource with the matching ID.
      parameters:
        - name: id
          in: path
          description: The ID of the resource to get
          required: true
          type: integer
          minimum: 1
      tags:
        - Resources
      responses:
        200:
          description: The requested resource
          schema:
            type: object
            properties:
              resource:
                $ref: '#/definitions/Resource'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Book:
    type: object
    properties:
      id:
        type: integer
        description: Unique identifier for the book.
      title:
        type: string
        description: Book title.
      author:
        type: string
        description: Book author.
      resources:
        type: array
        description: IDs for resources linked to this book.
        items:
          type: integer
  Resource:
    type: object
    properties:
      id:
        type: integer
        description: The resource's ID
      resource_type:
        type: string
        description: The type of resource
        # TODO - enum for these?
      text:
        type: string
        description: The text describing this resource
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
