package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// NewPostBooksParams creates a new PostBooksParams object
// with the default values initialized.
func NewPostBooksParams() PostBooksParams {
	var ()
	return PostBooksParams{}
}

// PostBooksParams contains all the bound params for the post books operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostBooks
type PostBooksParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*The book JSON you want to post
	  In: body
	*/
	Book PostBooksBody
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *PostBooksParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body PostBooksBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("book", "body", "", err))
		} else {

			if len(res) == 0 {
				o.Book = body
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
