package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"revised-server/models"
)

// NewPostBooksParams creates a new PostBooksParams object
// with the default values initialized.
func NewPostBooksParams() PostBooksParams {
	var ()
	return PostBooksParams{}
}

// PostBooksParams contains all the bound params for the post books operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostBooks
type PostBooksParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*The book JSON you want to post
	  Required: true
	  In: body
	*/
	Book *models.Book
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *PostBooksParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Book
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("book", "body"))
			} else {
				res = append(res, errors.NewParseError("book", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Book = &body
			}
		}

	} else {
		res = append(res, errors.Required("book", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
